# Nombre de la app
spring.application.name=football-tournaments

# Puerto donde corre la app
server.port=8080

# Database que cogemos los datos del .env (base de datos local)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Hacemos que Java pueda hablar con PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
# Si existen las tablas las actualiza, sino las crea
spring.jpa.hibernate.ddl-auto=update
# Para que salga en consola las consultas SQL que se ejecutan (para depuracion de errores)
spring.jpa.show-sql=true
# Para que salga formateado el SQL en la consola (para depuracion de errores)
spring.jpa.properties.hibernate.format_sql=true
# Dialecto de Hibernate para PostgreSQL, sino no sabria con que tipo de base de datos esta hablando
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf
# Para que Thymeleaf no cachee las plantillas (los cambios se ven sin reiniciar)
spring.thymeleaf.cache=false
# Para que Thymeleaf use UTF-8 y se muestren bien tildes y ñ
spring.thymeleaf.encoding=UTF-8

# Con false, si me he logueado antes y reinicio la app, me desloguea
server.servlet.session.persistent=false
# Duracion de la sesion sin actividad (30 minutos)
server.servlet.session.timeout=30m

# Tamano maximo de archivos que se pueden subir (imagenes de equipos)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# OAuth2 - Login con GitHub
# Le dice a Spring que el proveedor es GitHub y aqui estan sus credenciales (del .env)
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
# Permisos que pedimos a GitHub: solo leer perfil y email
spring.security.oauth2.client.registration.github.scope=read:user,user:email
